# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mrt8KqsdodsGlQhWtagZityET5UcKOuc
"""

def adicionar_tarefa(lista_tarefas, tarefa):
    lista_tarefas.append(tarefa)
    print("Tarefa adicionada com sucesso!")


def exibir_tarefas(lista_tarefas):
    print("\nTarefas pendentes:")
    if not lista_tarefas:
        print("Nenhuma tarefa pendente.")
    else:
        for i, tarefa in enumerate(lista_tarefas, start=1):
            print(f"{i}. {tarefa}")

#
def marcar_concluida(lista_tarefas, numero_tarefa):
    if 1 <= numero_tarefa <= len(lista_tarefas):
        lista_tarefas.pop(numero_tarefa - 1)
        print("Tarefa marcada como concluída.")
    else:
        print("Número de tarefa inválido.")



def main():
    lista_tarefas = []

    while True:
        print("\n1. Adicionar tarefa")
        print("2. Exibir tarefas")
        print("3. Marcar tarefa como concluída")
        print("4. Sair")

        opcao = input("Escolha uma opção: ")

        if opcao == '1':
            tarefa = input("Digite a tarefa a ser adicionada: ")
            adicionar_tarefa(lista_tarefas, tarefa)
        elif opcao == '2':
            exibir_tarefas(lista_tarefas)
        elif opcao == '3':
            numero_tarefa = int(input("Digite o número da tarefa concluída: "))
            marcar_concluida(lista_tarefas, numero_tarefa)
        elif opcao == '4':
            print("Saindo do programa...")
            break
        else:
            print("Opção inválida. Tente novamente.")

if __name__== "__main__":
    main()